spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quartz?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      #ddl-auto:设为update表示每次都不会重新建表
      ddl-auto: create
    show-sql: true
  application:
    name: quartz-cluster-node-first
servlet:
  port: 8081
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.springms: DEBUG
