spring :
  datasource :
    url : jdbc:mysql://localhost:3306/security?&useSSL=false
    username : root
    password : root
    driver-class-name: com.mysql.jdbc.Driver
#    platform: mysql
#    schema: classpath:/schema.sql
#    initialization-mode: embedded
mybatis :
  config-location : classpath:/mybatis/mybatis-config.xml
  mapper-location: classpath:/mybatis/mapper/*.xml
# JWT
jwt:
  header: Authorization
  secret: mySecret
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer "
