spring :
  datasource :
    url : jdbc:mysql://localhost:3306/security?&useSSL=false&serverTimezone=UTC
    username : root
    password : root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis :
  config-location : classpath:mybatis/mybatis-config.xml
#  mapper-location: classpath:mybatis/mapper/*.xml
# JWT
jwt:
  header: Authorization
  secret: mySecret
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer "

