# database相关
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rabbitmq?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
    # rabbitmq 相关
    rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    application:
    name: rabbitmq-plus
  # mail 相关
  mail:
    host: smtp.qq.com
    port: 465
    username: 280767840@qq.com
    password: didxobmmyzaibicf
    protocol: smtp
    from: 280767840@qq.com
    to: wangdadamailbox@163.com,280767840@qq.com
    by: 280767840@qq.com
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# mybatis 相关
mybatis:
  configuration:
    # 开启驼峰转换
    map-underscore-to-camel-case: true
    # 控制是否打印SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# logging 相关
logging:
  path: D:\\rabbitmq\\logs
  file: spring-boot-starter-parent
