spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quartz?useSSL=false
    username: root
    password: root
mybatis:
  configuration:
    # 控制是否打印SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰转换
    map-underscore-to-camel-case: true
